setwd("D:/SingleCellAnalysis/GSE130146/")

# This code prepares data for further analysis (up until normalization)
# The GEO-downloaded (GSE130146) values were downloaded from the database.
# R 3.12
# Generated by:  AJ Kinstlick (akinstlick@uchicago.edu)
# Last update: 08/24/2020

#---------------------------
mynormalization <- "Results/LibrarySize/"

#---------------------------
#data loading

library(DropletUtils)
fnameeb <- file.path("Data/EB/")
eb.sce <- read10xCounts(fnameeb, col.names=TRUE)

library(AnnotationHub)
ens.mm.v97 <- AnnotationHub()[["AH73905"]]
anno <- select(ens.mm.v97, keys=rownames(eb.sce), 
               keytype="GENEID", columns=c("SYMBOL", "SEQNAME"))
rowData(eb.sce) <- anno[match(rownames(eb.sce), anno$GENEID),]

library(AnnotationHub)
ens.mm.v97 <- AnnotationHub()[["AH73905"]]
chr.loc <- mapIds(ens.mm.v97, keys=rownames(eb.sce),
                  keytype="GENEID", column="SEQNAME")
is.mito <- which(chr.loc=="MT")
#snapshot date: 2020-4-27

#drop where total values are 0 in df
library(scater)
df <- perCellQCMetrics(eb.sce, subsets=list(Mito=is.mito))
df

save(eb.sce, file=paste0(mynormalization,"eb.sce.RData"), compress=TRUE)

#these steps worked, produced an annotated df with mito percents done
#now i need to drop where mito% > 5 or fewer than 5000 genes


#------------------------------------------------------
#filtering

#for filtering the cells, we followed the author's methods.

qc.nexprs <- df$detected < 2000
qc.mito <- df$subsets_Mito_percent > 5
discard <- qc.nexprs | qc.mito
DataFrame(NExprs=sum(qc.nexprs), MitoProp=sum(qc.mito), Total=sum(discard))


#[1] 737280     10
length(qc.nexprs)
#[1] 737280
table(qc.nexprs)
qc.nexprs
#FALSE   TRUE 
#2202 735078 
table(qc.mito)
qc.mito
#FALSE   TRUE 
#355411  44246 
table(discard)
discard
#FALSE   TRUE 
#1731 735549 
eb.sce
#class: SingleCellExperiment 
#dim: 33456 737280 
#metadata(1): Samples
#assays(1): counts
#rownames(33456): ENSMUSG00000064842 ENSMUSG00000051951 ... ENSMUSG00000096730 ENSMUSG00000095742
#rowData names(2): ID Symbol
#colnames(737280): AAACCTGAGAAACCAT-1 AAACCTGAGAAACCGC-1 ... TTTGTCATCTTTAGTC-1 TTTGTCATCTTTCCTC-1
#colData names(2): Sample Barcode
#reducedDimNames(0):
#altExpNames(0):

filtered <- eb.sce[,!discard]

dim(filtered)
#[1] 33456  1731

save(filtered,file=paste0(mynormalization,"ebfiltered.RData"))
