setwd('D:/SingleCellAnalysis/GSE130146/')

source("RCode/Myplot_cell_clusters.R")

load('Results/Deconvolution/intersects_binom.RData')

# This code attempts to identify clusters by marker genes.
# The marker genes were taken from table S1 from Zhao and Choi's Mouse EB dataset
# R 3.12
# Generated by:  AJ Kinstlick (akinstlick@uchicago.edu)
# Last update: 08/24/2020

markers = c("Sox2","T","Mesp1","Gata4","Tbx5","Nppa","Nkx2-5","Klf1","Tal1","Etv2",
            "Hand2","Fgfr2","Pou5f1","Nanog","Hand1","Ils1","Kdr")

#CARDIAC:
#Tagln, Lgals3, Krt19
# "Tpm1"   "Vim"    "Krt8"   "Tagln"  "Lgals3" "Tmsb4x" "Krt18"  "Phlda2" "Krt19"  "Tagln2"
#Gata3, Bmp4, Vim

newmarkers = c("Gata3","Bmp4","Vim")

newmarkers2 = c("Tagln","Lgals3","Krt19")

newmarkers3 = c("Vim","Krt19","Tagln","Lgals3","Tbx5","Isl1","Gata3","Mesp1")

newmarkers4 = c("Tnnt2", "Col3a1")

for(i in 1:2){
  print(newmarkers4[i])
  print(which(rowData(dimred.sce)$Symbol == newmarkers4[i]))
}

#stem to cardio: sox2
#meso: T, Mesp1
#cardiac: Ils1, Gata4, Tbx5
#cardiomyocyte: Mly7, Nppa, Nkx2-5

#Klf1 - heart and blood
#Tal1, Etv2 - HE
#Hand2, Fgfr2 - cardiomyocyte
markerrows = list()

markerrows = which(rowData(dimred.sce)$Symbol %in% newmarkers3)

sparselog = logcounts(dimred.sce)

expressionPlot = function(markerrows,dimred.sce,sparselog,pathdirect='./'){
  markermatrix = matrix(nrow=length(markerrows),ncol=ncol(dimred.sce))
  flag = 0
  for(i in markerrows){
    flag = flag + 1
    for(x in 1:ncol(dimred.sce)){
      markermatrix[flag,x] = sparselog[i,x]
    }
  }
  rownames(markermatrix) = rowData(dimred.sce)$Symbol[markerrows]
  return(markermatrix)
}



mytitle=rowData(dimred.sce)$Symbol[339]

mat = expressionPlot(339,dimred.sce,sparselog)

colData(dimred.sce)$temp = mat

plotReducedDim(dimred.sce, "TSNE", colour_by="temp") +
  ggtitle(mytitle)
  
dev.copy2pdf(file=paste0("Results/LibrarySize/tsne_expression_",mytitle,".pdf"))

colData(dimred.sce) <- subset(colData(dimred.sce), select = -c(temp))



save(mat_libsf,file=paste0("Results/LibrarySize/mat_libsf_",mytitle,".RData"))

#get expression graph, then upload to ubox


#use function to get markermatrix
colData(dimred.sce)$temp = markermatrix[flag,]

mytitle = rowData(dimred.sce)$Symbol[i]

plotReducedDim(dimred.sce, "TSNE", colour_by="temp") +
  ggtitle("Sox2")

dev.copy2pdf(file=paste0(pathdirect,"tsne_expression_",mytitle,".pdf"))


result = expressionPlot(markerrows[2],dimred.sce,sparselog,"Results/Deconvolution/")

pdf(file="Results/Deconvolution/scale_plot_markers.pdf",width=10,height=7)
plot_cell_clusters(cds, 1, 2 , color = "Cluster"
                   ,markers =  markers
                   ,show_cell_names = TRUE
)
plot_cell_clusters(cds, 3, 2 , color = "Cluster"
                   ,markers =  markers
                   ,show_cell_names = TRUE
)
Myplot_cell_clusters(cds, 1, 2, color = "cam.type",cell_shape='gate'
                     ,addValue=0
                     ,show_cell_names = TRUE
)                    
Myplot_cell_clusters(cds, 3, 2, color = "cam.type",cell_shape='gate'
                     ,addValue=0
                     ,show_cell_names = TRUE
)                    
Myplot_cell_clusters(cds, 1, 2, color = "Cluster",cell_shape='gate'
                     ,addValue=0
                     ,show_cell_names = TRUE
)                    
Myplot_cell_clusters(cds, 3, 2, color = "Cluster",cell_shape='gate'
                     ,addValue=0
                     ,show_cell_names = TRUE
)                    
dev.off()


Attachments area
