setwd("D:/SingleCellAnalysis/GSE130146/Results/Deconvolution/")

# This code analyzes mouse cell data using TSNE, clustering, and trajectory analysis
# The GEO-downloaded (GSE130146) values were normalized by deconvolution.
# R 3.12
# Generated by:  AJ Kinstlick (akinstlick@uchicago.edu)
# Last update: 08/24/2020

library(scran)
set.seed(100)
clust.filtered <- quickCluster(filtered) 
table(clust.filtered)

deconv.filtered <- calculateSumFactors(filtered, cluster=clust.filtered)
summary(deconv.filtered)


#report normalization methods
#compare them
#2 angles
#housekeeping genes - looks similar

#-----------------------------------------------
#Housekeeping
load(file="../myHK.RData")

HKsearch = toupper(rowData(filtered)$Symbol)
HKlist = which(HKsearch %in% myHK)
HKIDs = rowData(filtered)$ID[HKlist]
HKsymbols = rowData(filtered)$Symbol[HKlist]

#----------------------------------------------
#saving deconv data as sce object
set.seed(100)
#I already have clust.filtered
filteredsum <- computeSumFactors(filtered, cluster=clust.filtered, min.mean=0.1)
deconv.sce <- logNormCounts(filteredsum, size_factors=deconv.filtered)
assayNames(filteredsum)

save(deconv.sce,file="deconv.sce.RData",compress=TRUE)

#------------------------------------------------
#Feature Selection

library(scran)
lib.sce <- modelGeneVar(deconv.sce)

# Visualizing the fit:
fit.sce <- metadata(lib.sce)
plot(fit.sce$mean, fit.sce$var, xlab="Mean of log-expression",
     ylab="Variance of log-expression")
curve(fit.sce$trend(x), col="dodgerblue", add=TRUE, lwd=2)


lib.sce[order(lib.sce$bio, decreasing=TRUE),]

#--
deconv.var <- getTopHVGs(lib.sce, n=4000)
length(deconv.var)
#[1] 4000
str(deconv.var)

#--------------------------
#dimensionality reduction - run pca first, then 2 options: follow TSNE or UMAP
library(scater)
set.seed(100) # See below.
dimred.sce <- runPCA(deconv.sce, subset_row=deconv.var) 
reducedDimNames(dimred.sce)

dim(reducedDim(dimred.sce, "PCA"))

#--------------------------------
set.seed(00101001101)
dimred.sce <- runTSNE(dimred.sce, dimred="PCA")
plotReducedDim(dimred.sce, dimred="TSNE")

save(dimred.sce, file="Results/Deconvolution/dimred.sce.RData", compress=TRUE)

#----------------------------------

g <- buildSNNGraph(dimred.sce, k=5, use.dimred = 'PCA')
clust <- igraph::cluster_walktrap(g)$membership
table(clust)

#   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17 
# 301  77 234 293  24 131  68  50 143  40  49 123  28  74  51  12  33

colLabels(dimred.sce) <- factor(clust)

plotReducedDim(dimred.sce, "TSNE", colour_by="label")

#try running this with 3rd TSNE component

#is cardiac still close in 3rd dimension?
plotReducedDim(dimred.sce, "TSNE", colour_by="label")


dev.copy2pdf(file="clustering_tests_tsne.pdf")


#----------------------------------------------
#graphing housekeeping genes
library(scater)

plots <- list()

for(i in 1:27){
  as.ggplot(plotExpression(dimred.sce,
               x="label", 
               #                 colour_by="time",
               features=HKIDs[i]))
}

gridExtra::grid.arrange(
  grobs = for(i in 1:9){
    plotExpression(dimred.sce,
                   x="label", 
                   #                 colour_by="time",
                   features=HKIDs[i])
    }
)

gridExtra::grid.arrange(
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000006412") +
    ggtitle("Library Size Factors (1)"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000009549"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000074884"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000027620"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000002015"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000006699"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000029038"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000038803"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000015804")
)

dev.copy2pdf(file="HKDeconv1.pdf")

gridExtra::grid.arrange(
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000039771") +
    ggtitle("Library Size Factors (2)"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000019494"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000051695"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000030298"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000004667"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000074781"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000031879"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000084786"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000020457")
)

dev.copy2pdf(file="HKDeconv2.pdf")

gridExtra::grid.arrange(
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000021218") +
    ggtitle("Library Size Factors (3)"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000021037"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000022427"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000022400"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000001289"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000022961"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000024387"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000040385"),
  plotExpression(dimred.sce,
                 x="label", 
                 #                 colour_by="time",
                 features="ENSMUSG00000096994")
)

dev.copy2pdf(file="HKDeconv3.pdf")


#-----------------------------------

mymarkers = c("Etv2","Gata2","Tal1","Zfp42","Pou5f1","Kdr","Tbx20","Hand1","Mesp1")

markerids = which((rowData(filtered)$Symbol) %in% mymarkers)

markerids2 = rownames(filtered)[markerids]

markerlabels=rowData(filtered)$Symbol[markerids]

#plotExpression(dimred.sce, features=markerids2, 
#              x="label", colour_by="label")

gridExtra::grid.arrange(
  plotExpression(dimred.sce, features=markerids2[1], 
                 x="label", colour_by="label",
                 xlab=markerlabels[1]),
  plotExpression(dimred.sce, features=markerids2[2], 
                 x="label", colour_by="label",
                 xlab=markerlabels[2]),
  plotExpression(dimred.sce, features=markerids2[3], 
                 x="label", colour_by="label",
                 xlab=markerlabels[3]),
  plotExpression(dimred.sce, features=markerids2[4], 
                 x="label", colour_by="label",
                 xlab=markerlabels[4]),
  plotExpression(dimred.sce, features=markerids2[5], 
                 x="label", colour_by="label",
                 xlab=markerlabels[5]),
  plotExpression(dimred.sce, features=markerids2[6], 
                 x="label", colour_by="label",
                 xlab=markerlabels[6]),
  plotExpression(dimred.sce, features=markerids2[7], 
                 x="label", colour_by="label",
                 xlab=markerlabels[7]),
  plotExpression(dimred.sce, features=markerids2[8], 
                 x="label", colour_by="label",
                 xlab=markerlabels[8]),
  plotExpression(dimred.sce, features=markerids2[9], 
                 x="label", colour_by="label",
                 xlab=markerlabels[9]),
  ncol=3
)

dev.copy2pdf(file="expression_markers_deconv_k=5.pdf")


#cardiac - 
#hemangiogenic - maybe 1 and 15 combo
#smooth muscle - 
#naive pluripotent - looks like 10
#endoderm - looks like 2
#primordial germ - 

#more confusing bc groups are bigger
#i changed k but did not reanalyze this data,
#instead analyzing the later results
#with table s1

#---------------------------------------
#trajectory building, type 1

dimred.sce

library(scater)
by.cluster <- aggregateAcrossCells(dimred.sce, ids=colData(dimred.sce)$label)
centroids <- reducedDim(by.cluster, "PCA")

dmat <- dist(centroids)
dmat <- as.matrix(dmat)
g <- igraph::graph.adjacency(dmat, mode = "undirected", weighted = TRUE)
mst <- igraph::minimum.spanning.tree(g)

set.seed(1000)
plot(mst)

pairs <- Matrix::which(mst[] > 0, arr.ind=TRUE)
coords <- reducedDim(by.cluster, "TSNE")
group <- rep(seq_len(nrow(pairs)), 2)
stuff <- data.frame(rbind(coords[pairs[,1],], coords[pairs[,2],]), group)

plotTSNE(dimred.sce, colour_by="label") + 
  geom_line(data=stuff, mapping=aes(x=X1, y=X2, group=group))

dev.copy2pdf(file="trajectory_deconv_1.pdf")


#-------------------------------
#trajectory building, type 2

#try to remove clusters 17 and 2 for this analysis

.map2edges <- function(points, center, edge.ends, previous) {
  all.distances <- list()
  all.pseudo <- list()
  edge.len <- list()
  
  # Computing distance of each point from each edge.
  # Edges defined from 'center' to 'edge.ends'.
  for (i in rownames(edge.ends)) {
    edge.end <- edge.ends[i,]
    delta <- center - edge.end
    max.d <- sqrt(sum(delta^2))
    delta <- delta/max.d
    
    centered <- t(t(points) - center)
    proj <- as.numeric(centered %*% delta)
    proj <- pmax(0, pmin(proj, max.d))
    mapped <- outer(proj, delta)
    
    dist <- sqrt(rowSums((centered - mapped)^2))
    all.distances[[i]] <- dist
    all.pseudo[[i]] <- proj
    edge.len[[i]] <- max.d
  }
  
  all.distances <- do.call(cbind, all.distances)
  all.pseudo <- do.call(cbind, all.pseudo)
  chosen <- colnames(all.distances)[max.col(-all.distances)]
  
  # Flipping the distance of points to the previous node,
  # in order to enforce a directional pseudo-time.
  dist.previous <- 0
  if (!is.na(previous)) {
    on.previous <- chosen==previous
    dist.previous <- edge.len[[previous]]
    previous.proj <- dist.previous - all.pseudo[on.previous,previous,drop=FALSE]
    
    if (all(on.previous)) {
      return(list(dist=dist.previous, pseudo=list(previous.proj)))
    }
  }
  
  # Filling out the branches, where points are NA for a branch's
  # pseudo-time if they were assigned to another branch.
  output <- list()
  for (leftover in setdiff(rownames(edge.ends), previous)) {
    empty <- rep(NA_real_, nrow(points))
    if (!is.na(previous)) {
      empty[on.previous] <- previous.proj
    }
    current <- chosen==leftover
    empty[current] <- all.pseudo[current,leftover]
    output[[leftover]] <- empty
  }
  
  list(dist=dist.previous, pseudo=output)
}

originals <- reducedDim(dimred.sce, "PCA")
cluster <- colLabels(dimred.sce)
starting.cluster <- names(igraph::V(mst)[igraph::degree(mst)==1])[1]
collated <- list()

latest <- starting.cluster
parents <- NA_character_ 
progress <- list(rep(NA_real_, length(cluster)))
cumulative <- 0

while (length(latest)) {
  new.latest <- new.parents <- character(0)
  new.progress <- list()
  new.cumulative <- numeric(0)
  
  for (i in seq_along(latest)) {
    curnode <- latest[i]
    all.neighbors <- names(igraph::adjacent_vertices(mst, curnode, mode="all")[[1]])
    in.cluster <- cluster==curnode 
    
    mapped <- .map2edges(originals[in.cluster,,drop=FALSE], center=centroids[curnode,], 
                         edge.ends=centroids[all.neighbors,,drop=FALSE], previous=parents[i])
    edge.len <- mapped$dist
    pseudo <- mapped$pseudo
    
    collected.progress <- list()
    for (j in seq_along(pseudo)) {
      sofar <- progress[[i]] # yes, using 'i' here.
      sofar[in.cluster] <- pseudo[[j]] + cumulative[i]
      collected.progress[[j]] <- sofar
    }
    
    all.children <- setdiff(all.neighbors, parents[i])
    if (length(all.children)==0) {
      collated[[curnode]] <- collected.progress[[1]]
    } else {
      new.latest <- c(new.latest, all.children)
      new.parents <- c(new.parents, rep(curnode, length(all.children)))
      new.progress <- c(new.progress, collected.progress)
      new.cumulative <- c(new.cumulative, rep(cumulative[i] + edge.len, length(all.children)))
    }
  }
  
  latest <- new.latest
  parents <- new.parents
  progress <- new.progress
  cumulative <- new.cumulative
}
tscan.pseudo <- do.call(cbind, collated)

plotTSNE(dimred.sce, colour_by=I(rowMeans(tscan.pseudo, na.rm=TRUE)), text_by="label") +
  geom_line(data=stuff, mapping=aes(x=X1, y=X2, group=group))

dev.copy2pdf(file="trajectory_deconv_2.pdf")



#-----------------------------------------
#more marker gene analysis - using table s1 data
#-------------------------------------------
#opening table S1 markers for analysis
load(file="../markerS1.RData")
#------------------------------------------
#finding marker genes
topvals = 10
#adjust analysis with this
#ALSO ADJUST IN TABLES1 CODE

markers.binom <- findMarkers(dimred.sce, test="binom", direction="up")
names(markers.binom)

library(scater)

markerEB <- list()
for (i in 1:length(markers.binom)){
  interesting.binom <- markers.binom[[i]]
  top.genes <- row.names(interesting.binom[interesting.binom$Top <= topvals,])
  #top.genes <- head(rownames(interesting.binom), topvals)
  barcode.list <- which(rowData(dimred.sce)$ID %in% top.genes)
  markerEB[[i]] = rowData(dimred.sce)$Symbol[barcode.list]
}



#-----------------------------------------
#analyzing binomial tests

#our old assumptions - i think this was when i had k = 10
#cardiac - 
#hemangiogenic - maybe 1 and 15 combo
#smooth muscle - 
#naive pluripotent - looks like 10
#endoderm - looks like 2
#primordial germ - 

#--------
#new info

#cardiac - matches for 10
#hemangiogenic - matches for 13
#smooth muscle - matches for 7
#naive pluripotent - 8 for sure
#endoderm - mix of 14 and 9, 14 a bit higher
#primordial germ - 11 and 12



intersects.binom <- list()
for (i in 1:length(markerEB)){
  intersects.binom[[i]] = unlist(lapply(markerS1,function(X) intersect(X,markerEB[[i]])))
}

save(intersects.binom, file="intersects_binom.RData")

targets = c("cardiac", "hemangiogenic", "smooth muscle", "naive pluripotent", "endoderm", "primordial germ")

par(mfrow = c(2,3))

for(i in targets){
  temp = lapply(intersects.binom, function(x) length(grep(i, names(x))) / length(x))
  plot(unlist(temp),main=i)
}

dev.copy2pdf(file=paste0("binomgroupproportions_",topvals,".pdf"))


#figure out where cardiac is

#repeat analysis with t test

#-----------------------------------------
#t-test marker gene analysis
markers.ttest <- findMarkers(dimred.sce)
names(markers.ttest)

library(scater)
markerEBttest <- list()

for (i in 1:length(markers.ttest)){
  interesting.ttest <- markers.ttest[[i]]
  top.genes <- interesting.ttest[interesting.ttest$Top <= topvals,]
  barcode.list <- which(rowData(dimred.sce)$ID %in% row.names(top.genes))
  markerEBttest[[i]] = rowData(dimred.sce)$Symbol[barcode.list]
}

intersects.ttest <- list()
for (i in 1:length(markerEBttest)){
  intersects.ttest[[i]] = unlist(lapply(markerS1,function(X) intersect(X,markerEBttest[[i]])))
}

save(intersects.ttest, file="intersects_ttest.RData", compress=TRUE)


targets = c("cardiac", "hemangiogenic", "smooth muscle", "naive pluripotent", "endoderm", "primordial germ")

par(mfrow = c(2,3))

for(i in targets){
  temp = lapply(intersects.ttest, function(x) length(grep(i, names(x))) / length(x))
  plot(unlist(temp),main=i)
}

dev.copy2pdf(file=paste0("ttestgroupproportions_",topvals,".pdf"))


#run proportional analysis for binomial tests

#--------------------
#wilcox analysis
markers.wilcox <- findMarkers(dimred.sce, test="wilcox", direction="up")
names(markers.wilcox)

library(scater)
markerEBwilcox <- list()

for (i in 1:length(markers.wilcox)){
  interesting.wilcox <- markers.wilcox[[i]]
  top.genes <- interesting.wilcox[interesting.wilcox$Top <= topvals,]
  barcode.list <- which(rowData(dimred.sce)$ID %in% row.names(top.genes))
  markerEBwilcox[[i]] = rowData(dimred.sce)$Symbol[barcode.list]
}

intersects.wilcox <- list()
for (i in 1:length(markerEBwilcox)){
  intersects.wilcox[[i]] = unlist(lapply(markerS1,function(X) intersect(X,markerEBwilcox[[i]])))
}

save(intersects.wilcox, file="intersects_wilcox.RData", compress=TRUE)


targets = c("cardiac", "hemangiogenic", "smooth muscle", "naive pluripotent", "endoderm", "primordial germ")

par(mfrow = c(2,3))

for(i in targets){
  temp = lapply(intersects.wilcox, function(x) length(grep(i, names(x))) / length(x))
  plot(unlist(temp),main=i)
}

dev.copy2pdf(file=paste0("wilcoxgroupproportions_",topvals,".pdf"))







